# Publish a build for release.
name: KMMBridge-Release
on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  call-publish:
    uses: ./.github/workflows/Base-Publish.yml
    with:
      build-debug: false